### ISSUE TITLE
<p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>

### ISSUE THREAD

**Issue by lcm1475** [mzbac/chatgpt-plus-api-client#25]
<p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>

Can you write an example containing env files

**Comment by mzbac** [comment]
Please refer to the document [here](https://github.com/mzbac/chatgpt-plus-api-client#getting-chatgpt_cookies-from-cookies) to get cookie and authentication token.

.env file

```
CHATGPT_COOKIES=your_cookies_value_here
CHATGPT_AUTH_TOKEN=your_auth_token_value_here
```
