### ISSUE TITLE
polling_error

### ISSUE THREAD

**Issue by qiangweihewu** [mzbac/chatgpt-plus-api-client#30]
How to solve this error? Thanks!

> error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}

**Comment by mzbac** [comment]
This error message is related to Telegram Bot API and indicates that there are multiple instances of the same Telegram bot running at the same time, and they are conflicting with each other. To resolve this issue, you should ensure that only one instance of your bot is running at any given time.

Here are some steps you can follow to resolve this issue:

Check if there are any other instances of the same bot running. If you have multiple instances running, you need to shut them down.

If you're running your bot locally, ensure that you have stopped all instances of the bot running on your machine. You can also try restarting your machine to ensure that no processes are running.

If you're using a cloud-based service to run your bot, such as Heroku or AWS, check if there are any other instances of your bot running in the cloud. You can use the service's web interface or command-line tools to check this.

Finally, if you're still encountering the error, you can try contacting Telegram's support team for further assistance.
